### ISSUE TITLE
[Calendar] - Off-center date selectors

### ISSUE THREAD

**Issue by msparkman** [bullhorn/novo-elements#433] opened 2017-03-10 21:57 UTC
_**Note: for support questions, please use one of these channels:**_ [Chat: BullhornOSS Gitter](https://gitter.im/bullhorn/Open-Source)

##### **What is the current behavior?**
The calendar picker appears to have off-center selectors on the dates. Some dates seem to be slightly to the right in the circle while others appears slightly to the left. Same for vertical alignment.

##### **What is the expected behavior?**
Centered dates inside selection circles.

##### **Please tell us about your environment:**

- Angular version: 2.0.0-RC.X
- Browser: Chrome Version 55.0.2883.87 (64-bit)

##### **Other information**
![selection_007](https://cloud.githubusercontent.com/assets/6940808/23814535/7e1fa660-05a9-11e7-80ec-b543997c9a79.png)
![selection_008](https://cloud.githubusercontent.com/assets/6940808/23814541/818c1ff4-05a9-11e7-8924-997d719c98fb.png)

**Comment by jgodi** [comment] 2017-03-17 19:09
Closing, cannot reproduce anymore.

**Closed by jgodi** 2017-03-17 19:09 UTC
